"""Per-job progress store for backup / restore runs.

Mirror of :mod:`backend.server.install_progress`, keyed by an opaque
``job_id`` (UUID generated by the route handler that spawns the worker
thread). Job IDs are globally unique, so we don't need to scope by
server — the frontend polls ``GET /api/backup-jobs/<job_id>``.

Phase vocabulary (set by ``backups/service.py`` and ``backups/restore.py``):

    starting        — worker thread spawned
    flushing        — issuing save-all flush + waiting for confirmation
    stopping_server — graceful shutdown in progress
    staging         — copytree to .staging-<...> with exclusions applied
    archiving       — building tar / tar.gz outputs
    finalizing      — atomic publish to storagePath + retention
    restarting      — bringing the server back if it was running
    safety_snapshot — restore/import: writing the mandatory safety .tar
    extracting      — restore: unpacking the chosen snapshot;
                      import: unpacking the uploaded archive
    converting      — import: detecting layout + normalising world dirs
    overlaying      — restore in_place: copying staging on top of live dir
    swapping        — restore reset / import: atomic rename of staged tree
    done            — completed successfully (terminal)
    failed          — failed (entry has ``error``; terminal)

Terminal phases flip ``is_active`` to False so the frontend's poll loop
knows to stop. A missing entry also returns False — useful when the
backend restarts mid-job and the in-memory dict is wiped.
"""
from __future__ import annotations

import threading
import uuid
from typing import Any, Dict

from backend.utils.time import iso_z_now


_lock = threading.Lock()
_store: Dict[str, Dict[str, Any]] = {}

_TERMINAL_PHASES = frozenset({"done", "failed"})


def update(job_id: str, /, **kwargs: Any) -> None:
    """Merge ``kwargs`` into the entry for ``job_id``.

    ``job_id`` is positional-only so callers may also pass ``job_id=<value>``
    as a payload kwarg. ``updated_at`` is set on every call so the frontend
    can detect staleness. Earlier keys are preserved when not overwritten.
    """
    timestamp = iso_z_now()
    with _lock:
        existing = _store.get(job_id) or {}
        _store[job_id] = {
            **existing,
            **kwargs,
            "updated_at": timestamp,
        }


def get(job_id: str, /) -> Dict[str, Any]:
    """Return a copy of the entry for ``job_id``, or ``{}`` if missing."""
    with _lock:
        return dict(_store.get(job_id) or {})


def clear(job_id: str, /) -> None:
    """Drop the entry for ``job_id``. No-op if missing."""
    with _lock:
        _store.pop(job_id, None)


def is_active(job_id: str, /) -> bool:
    """True iff there's an entry whose phase isn't terminal."""
    with _lock:
        entry = _store.get(job_id)
        if not entry:
            return False
        phase = entry.get("phase")
        if not phase:
            return False
        return phase not in _TERMINAL_PHASES


def generate_job_id(prefix: str) -> str:
    """Return a unique job ID with the given prefix, e.g. ``bjb_<12-hex>``."""
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


def reset_for_tests() -> None:
    """Wipe the in-memory store. Tests only."""
    with _lock:
        _store.clear()
