"""Generate fabricator.spec for PyInstaller Windows builds."""
from pathlib import Path


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    spec_path = script_dir / "fabricator.spec"

    # Data files to bundle: frontend/dist (must exist after npm run build)
    datas = []
    frontend_dist = script_dir / "frontend" / "dist"
    if frontend_dist.exists():
        datas.append((str(frontend_dist), "frontend/dist"))
    else:
        print("WARNING: frontend/dist not found. Run 'npm run build' in frontend/ first.")

    # Optional assets folder for tray icon
    assets_dir = script_dir / "assets"
    icon_path = assets_dir / "icon.ico"
    if assets_dir.exists():
        datas.append((str(assets_dir), "assets"))

    icon_arg = f"icon={repr(str(icon_path))}," if icon_path.exists() else ""

    datas_str = ",\n    ".join(f'("{src}", "{dst}")' for src, dst in datas)

    spec_content = f'''# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by generate_spec.py - do not edit manually

block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[
    {datas_str}
    ],
    hiddenimports=[
        'backend',
        'backend.core',
        'backend.core.app',
        'backend.core.config',
        'backend.server',
        'backend.server.routes',
        'backend.server.manager',
        'backend.server.storage',
        'backend.server.registry',
        'backend.server.installer',
        'backend.server.installer.fabric',
        'backend.modrinth',
        'backend.modrinth.routes',
        'backend.modrinth.client',
        'backend.utils',
        'backend.utils.platform',
        'flask',
        'flask_cors',
        'werkzeug.serving',
        'werkzeug.wrappers',
        'pystray',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'requests',
        'psutil',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Fabricator',
    {icon_arg}
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
'''

    spec_path.write_text(spec_content, encoding="utf-8")
    print(f"Generated {spec_path}")


if __name__ == "__main__":
    main()
