"""Abstract base class for Minecraft server installers."""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import List, Optional, Dict, Any


class InstallStatus(Enum):
    """Installation status enum."""
    PENDING = "pending"
    DOWNLOADING = "downloading"
    INSTALLING = "installing"
    CONFIGURING = "configuring"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class InstallResult:
    """Result of an installation attempt."""
    success: bool
    status: InstallStatus
    message: str
    server_jar: Optional[Path] = None
    details: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "success": self.success,
            "status": self.status.value,
            "message": self.message,
            "server_jar": str(self.server_jar) if self.server_jar else None,
            "details": self.details
        }


class InstallerBase(ABC):
    """Abstract base class for Minecraft server installers."""

    def __init__(self, install_path: Path):
        """Initialize installer with target path.
        
        Args:
            install_path: Directory where server will be installed
        """
        self.install_path = Path(install_path)

    @property
    @abstractmethod
    def loader_name(self) -> str:
        """Return the name of the mod loader (e.g., 'fabric', 'forge')."""
        pass

    @abstractmethod
    def get_available_versions(self, mc_version: Optional[str] = None) -> List[Dict[str, Any]]:
        """Get available loader versions.
        
        Args:
            mc_version: Optional Minecraft version to filter by
            
        Returns:
            List of available versions with metadata
        """
        pass

    @abstractmethod
    def get_minecraft_versions(self) -> List[Dict[str, Any]]:
        """Get supported Minecraft versions.
        
        Returns:
            List of supported Minecraft versions
        """
        pass

    @abstractmethod
    def install(
        self,
        mc_version: str,
        loader_version: Optional[str] = None
    ) -> InstallResult:
        """Install the server.
        
        Args:
            mc_version: Minecraft version to install
            loader_version: Optional specific loader version (uses latest if None)
            
        Returns:
            InstallResult with success status and details
        """
        pass

    def _ensure_install_dir(self) -> None:
        """Create installation directory if it doesn't exist."""
        self.install_path.mkdir(parents=True, exist_ok=True)

    def _write_eula(self, accepted: bool = True) -> Path:
        """Write eula.txt file.
        
        Args:
            accepted: Whether EULA is accepted
            
        Returns:
            Path to eula.txt
        """
        eula_path = self.install_path / "eula.txt"
        eula_path.write_text(f"eula={'true' if accepted else 'false'}\n")
        return eula_path

    def _write_server_properties(self, properties: Dict[str, Any]) -> Path:
        """Write server.properties file.
        
        Args:
            properties: Dictionary of server properties
            
        Returns:
            Path to server.properties
        """
        props_path = self.install_path / "server.properties"
        
        lines = ["# Minecraft Server Properties", "# Generated by Fabricator"]
        for key, value in properties.items():
            # Convert Python types to properties format
            if isinstance(value, bool):
                value = str(value).lower()
            lines.append(f"{key}={value}")
        
        props_path.write_text("\n".join(lines) + "\n")
        return props_path

    def generate_server_properties(self, server_config: Dict[str, Any]) -> Dict[str, Any]:
        """Generate server.properties from server configuration.
        
        Args:
            server_config: Server configuration from storage
            
        Returns:
            Dictionary of server.properties values
        """
        # Map our config keys to server.properties keys
        return {
            "server-port": server_config.get("port", 25565),
            "max-players": server_config.get("maxPlayers", 20),
            "difficulty": server_config.get("difficulty", "normal"),
            "gamemode": server_config.get("gamemode", "survival"),
            "view-distance": server_config.get("viewDistance", 10),
            "simulation-distance": server_config.get("simulationDistance", 10),
            "level-name": server_config.get("levelName", "world"),
            "level-type": f"minecraft:{server_config.get('levelType', 'normal')}",
            "level-seed": server_config.get("seed", ""),
            "generate-structures": server_config.get("generateStructures", True),
            "spawn-animals": server_config.get("spawnAnimals", True),
            "spawn-monsters": server_config.get("spawnMonsters", True),
            "spawn-npcs": server_config.get("spawnNpcs", True),
            "online-mode": server_config.get("onlineMode", True),
            "white-list": server_config.get("whitelist", False),
            "pvp": server_config.get("pvp", True),
            "enable-command-block": server_config.get("commandBlocks", True),
            "motd": server_config.get("motd", "A Minecraft Server"),
        }
